# -*- coding: utf-8 -*-
"""Projeto1_DIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cVRvq925zT6PqjTD-rHyw1xxZPaLhCRr
"""

#Importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("classic")

#Upload do arquivo
from google.colab import files
arq = files.upload()

#Criando nosso DataFrame
df = pd.read_excel("ds_salaries.xlsx")

df.head()

#Deletando colunas
df = df.drop(columns=["Unnamed: 0", "employment_type", "salary_in_usd", "employee_residence"])
df.head()

#Renomeando colunas
df = df.rename(columns={"work_year": "Ano Trabalho", "experience_level": "Nivel Experiencia", "job_title": "Cargo", "salary": "Salario/Ano", "salary_currency": "Moeda", 
                        "remote_ratio": "Proporção Remota", "company_location": "Localização Empresa", "company_size": "Tamanho da Empresa"})
df.head()

#Quantidade de linhas e colunas
df.shape

#Media de Salario/Ano por Experiencia
df.groupby("Nivel Experiencia")["Salario/Ano"].mean().round(2).sort_values(ascending=True).plot.barh(title="Media Salario/Ano x Experiencia")
plt.xlabel("Salario/Ano")
plt.ylabel("Experiencia")

#Top 10 cargos que mais pagam em média
df.groupby("Cargo")["Salario/Ano"].mean().round(2).head(10).sort_values(ascending=False).plot.bar()

#Quantidade de Empregos x Ano
df.groupby(["Ano Trabalho"]).size().plot.bar()
plt.xlabel("Ano")
plt.ylabel("Contratações")

#Top 5 países que mais pagaram por ano
df.groupby("Localização Empresa")["Salario/Ano"].sum().round(2).head(5).sort_values(ascending=False).plot.bar()

#Qual tamanho de empresa mais contrata?
df.groupby("Tamanho da Empresa").size().sort_values(ascending=False).plot.bar()
plt.ylabel("Contratações")

#Mostra a proporção de trabalhadores 100% home office, 50% home office e totalmente presencial.
df.groupby("Proporção Remota").size().plot.pie(autopct="%1.1f%%", shadow=True, title="Proporção Remota")
plt.ylabel("")

